### ISSUE TITLE
create manual of BeLL-Apps out of google doc

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/open-learning-exchange.github.io#590]
There is [a manual](https://docs.google.com/document/d/1ikNCxVEJq22K8kcqkZIe0ibGDvL_1gMSl3Vk2F1_O8w/edit?usp=sharing) we would like converted from a google document to a mark down file. Everyone who works on this issue should make one pull request per section of the document that they convert to markdown. You should add your section to [this existing markdown file (tg-planet-user-manual.md)](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/techgenius/tg-planet-user-manual.md). Please comment here when you start converting a section so that others do not work on the same section as you. You will also need to upload the images. If you see anything that needs to be improved (grammar, phrasing, spelling, etc) go ahead an improve it.

Below is the list of sections, those that are checked off have already been done. Once your pull request has been merged the section will be checked off this list.

**Sections**
- [x] [**DONE**] Open Learning Exchange (#598 by @zeivhann) 
- [x] [**DONE**]  The PLANET Learning System / Overview (#607 by @kylemathias)
- [x] [**DONE**] How do I navigate and use PLANET? (#619 by @Supriyaranjan)
- [x] [**DONE**] Library and Resources Overview (https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/661 by @Loshma93)
- [ ] [**IN PROGRESS**] Courses Overview (https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/664 by @sarah-lu102)
- [x] [**DONE**] Members Overview (#654 by @mappuji)
- [ ] [**IN PROGRESS**] Reports Overview (@shahswet) 
- [x] [**DONE**] Feedback Overview (#822 by @Yurockkk)
- [x] [**DONE**] Language Overview (@Loshma93)
- [x] [**DONE**] Calendar Overview (@Loshma93)
- [ ] [**IN PROGRESS**] Email Overview (@Loshma93)
- [ ] [**IN PROGRESS**] Survey Overview (@Loshma93)
- [ ] Publication Overview
- [ ] Software Overview
- [x] [**DONE**] How do I receive a software update for my Community? (#1775 by @NirmalKumarJoshi)

**Comment by dogi** [comment]
This is a big meta issue, which should be split into tinier sub-issues ...
and this issues again should be solved by `pull requests`

**Comment by waryhermit** [comment]
@dogi I have made it into a list, I though splitting it into issues would clutter up the issue list too much.

**Comment by dogi** [comment]
@waryhermit thanks

**Comment by kylemathias** [comment]
Ill work on The PLANET Learning System / Overview

**Comment by kylemathias** [comment]
BTW: While you are converting this document, look for improvements/proof read the document as well. Would be a big help.

**Comment by waryhermit** [comment]
@kylemathias Thanks, I added that to the main post.

**Comment by Supriyaranjan** [comment]
I am working on "How do I navigate and use PLANET?"

**Comment by dogi** [comment]
@Supriyaranjan great ;)

**Comment by Loshma93** [comment]
I will be working on Library and Resource overview

**Comment by sarah-lu102** [comment]
I can work on courses overview! Also, does it matter if we do it on our local files and use the git commands to commit and push, or can we just edit it through github.com as a branch and submit the pull request?

**Comment by waryhermit** [comment]
@sarah-lu102 Doesn't matter to me.

**Comment by shahswet** [comment]
I will start working on Reports Overview :)

**Comment by Supriyaranjan** [comment]
@all @dogi  yesterday I was going through the planetusermanual.md and I saw one section "Members menu". But did not see that in the original document.
![image](https://cloud.githubusercontent.com/assets/26332034/25307907/4c219410-276f-11e7-9b93-21f56088a371.png)

**Comment by waryhermit** [comment]
@Supriyaranjan It looks like @mappuji took the *Members Overview* section and expanded it with more content, and called it *Members menu*. You can see that here in his pull request, #654. As stated in the original post we are aiming to improve the manual as we go, so that is probably why. If you do not think it was well done, I recommend contacting @mappuji

**Comment by Supriyaranjan** [comment]
@waryhermit @mappuji i think the new one is short and on the point

**Comment by Supriyaranjan** [comment]
I was not aware of this change as I was not very active on OlE for last few days

**Comment by Yurockkk** [comment]
I can work on "Feedback Overview" if it hasn't been taken : )

**Comment by Loshma93** [comment]
@dogi I am working on Language Overview and Calendar Overview

**Comment by NirmalKumarJoshi** [comment]
I would like to work on **How do I receive a Publication on my Community?** manual. Can I proceed?
